services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ":80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ":3001"
      - ":3002"
    environment:
      - NODE_ENV=
      - PORT=3001
      - SIGNAL_PORT=
      - SIGNAL_PATH=/ws
      - REDIS_URL=
      - DOMAIN=
      - JWT_SECRET=
      - TURN_SECRET=
      - TURN_DOMAIN=
      - TURN_PORT=
      - TURN_TLS_PORT=
      - MAX_PEERS_PER_CALL=
      - INACTIVE_TTL_SECONDS=
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - ":6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  coturn:
    image: coturn/coturn:latest
    ports:
      - ":3478"
      - ":3478/udp"
      - ":5349"
    environment:
      - TURN_USERNAME=
      - TURN_PASSWORD=
      - TURN_REALM=
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - ":80"
      - ":443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
