version: '3.8'

services:
  # Frontend (React SPA)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend (Node.js + WebSocket)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-3001}:${PORT:-3001}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - TURN_SERVER=${TURN_SERVER:-turn:38.180.153.25:3478}
      - TURN_USERNAME=${TURN_USERNAME:-turnuser}
      - TURN_PASSWORD=${TURN_PASSWORD:-turnpass}
      - DOMAIN=${DOMAIN:-tgcall.space}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    depends_on:
      - redis
      - coturn
    networks:
      - app-network

  # Redis для хранения состояния звонков
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  # TURN/STUN сервер
  coturn:
    image: coturn/coturn:latest
    ports:
      - "${TURN_UDP_PORT:-3478}:3478"
      - "${TURN_UDP_PORT:-3478}:3478/udp"
      - "${TURN_TLS_PORT:-5349}:5349"
    environment:
      - TURN_USERNAME=${TURN_USERNAME:-turnuser}
      - TURN_PASSWORD=${TURN_PASSWORD:-turnpass}
      - TURN_REALM=${TURN_REALM:-tgcall.space}
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - app-network

  # Nginx (существующая конфигурация)
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
